### ISSUE TITLE
Accessibilité de la recherche Pagefind

### ISSUE THREAD

**Issue by arnaudlevy** [osunyorg/theme#678]
- [x] Bloquant : Absence d’étiquette visible sur le champ de recherche [11.1](https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/#11.1)
- [x] Majeur : Présence d’une liste ordonnée sans contenu [9.3](https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/#9.3)
- [x] Majeur : Absence de restitution du nombre de résultats [7.5](https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/#7.5)

## Absence d’étiquette visible sur le champ de recherche
> Soit ajouter un attribut title avec une valeur pertinente sur le champ (lui donner la même valeur que le placeholder), soit utiliser la technique du floating label.

## Présence d’une liste ordonnée sans contenu
> Supprimer la liste ordonnée sans contenu

## Absence de restitution du nombre de résultats
> Implémenter dans le code HTML le bloc `<div class=”resultat_saisie” aria-live=”polite”></div>` au chargement de la page sans aucun contenu 
> Intégrer le contenu lors de l’affichage du panneau des suggestions

Code type attendu au chargement de la page :
```html
<div class="resultat_saisie" aria-live="polite"></div>
```
Code type attendu à l’affichage des suggestions :
```html
<div class="resultat_saisie" aria-live="polite"><p>10 résultats pour exemple</p></div>
```
Code type attendu en l&#39;absence de résultat :
```html
<div class="resultat_saisie" aria-live="polite"><p>Pas de résultat pour dfgdfgdfg</p></div>
```

**Comment by arnaudlevy** [comment]
En 9.3.2, le RGAA précise qu'il faut utiliser des ol et des li.
Il est tout à fait correct d'utiliser un ol vide pour indiquer une liste vide (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ol).
Je pense que la préconisation est erronée, parce que : 
- une liste vide est plus juste sémantiquement qu'une absence de liste
- une liste vide est correcte du point de vue HTML
- la méthodologie du test 9.3.2 ne traite pas le cas zero-li, ni dans un sens ni dans l'autre
Il me semble qu'il s'agit là d'une interprétation fausse de la phrase "La liste utilise les balises HTML <ol> et <li>", et qu'il faut se conformer à la spec HTML.

**Comment by arnaudlevy** [comment]
Sur le 3e point, il me semble que nous contrevenons aux points 7.5.1 ou 7.5.3 parce qu'il n'y a pas d'attribut role. 
En revanche, je ne vois rien qui oblige à avoir un div vide.

Par ailleurs, l'aria-live polite vaut `role=log`, ce qui est pertinent pour un message de progression.
Mais c'est faux, il s'agit du résultat d’une action, donc il faut : 
- soit `role="status"` 
- soit `aria-live="polite"` et un attribut WAI-ARIA `aria-atomic="true"`
